import React from 'react';

export const needs = [
  "connection",
  "acceptance",
  "affection",
  "appreciation",
  "belonging",
  "cooperation",
  "communication",
  "closeness",
  "community",
  "companionship",
  "compassion",
  "consideration",
  "consistency",
  "empathy",
  "inclusion",
  "intimacy",
  "love",
  "mutuality",
  "nurturing",
  "respect / self - respect",
  "safety",
  "security",
  "stability",
  "support",
  "to know and be known",
  "to see and be seen",
  "to understand and be understood",
  "trust",
  "warmth",
  "physical well - being",
  "air",
  "food",
  "movement / exercise",
  "rest / sleep",
  "sexual expression",
  "safety",
  "shelter",
  "touch",
  "water",
  "honesty",
  "authenticity",
  "integrity",
  "presence",
  "play",
  "joy",
  "humor",
  "peace",
  "beauty",
  "communion",
  "ease",
  "equality",
  "harmony",
  "inspiration",
  "order",
  "autonomy",
  "choice",
  "freedom",
  "independence",
  "space",
  "spontaneity",
  "meaning",
  "awareness",
  "celebration of life",
  "challenge",
  "clarity",
  "competence",
  "consciousness",
  "contribution",
  "creativity",
  "discovery",
  "efficacy",
  "effectiveness",
  "growth",
  "hope",
  "learning",
  "mourning",
  "participation",
  "purpose",
  "self - expression",
  "stimulation",
  "to matter",
  "understanding"
];

// A list of needs as options for a Select element
export const needsList = needs.map((need, i) => <option key={i} value={need}>{need}</option>);